Crucially, it:
  [ ] Responds to "yiff" "/yiff" with a random yiff image.
      [X] Connect to telegram with polling for debugging
      [ ] Connect to telegram with webhooks
      [X] Handle "yiff" as a command
      [/] Have a database of images
Additionally, it:
  Is written with as few lines of code as practicable.

In future, it should:
  [ ] Regularly poll e621 and add popular posts to its database.
  [ ] Allow configuration on a per group and per user level.

Issues:
  [ ] Telegram does not accept images larger than 5Mb when sending via url
